//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAN.ZHAN.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Attendance
    {
        public int a_id { get; set; }
        public Nullable<int> e_id { get; set; }
        public Nullable<System.DateTime> a_time { get; set; }
        public Nullable<int> m_id { get; set; }
        public Nullable<int> a_attend { get; set; }
    
        public virtual HR_Employee HR_Employee { get; set; }
        public virtual HR_MeettingSetting HR_MeettingSetting { get; set; }
    }
}
