//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAN.ZHAN.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_ClassRoom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HR_ClassRoom()
        {
            this.HR_NightDutyReport = new HashSet<HR_NightDutyReport>();
        }
    
        public int room_no { get; set; }
        public string room_name { get; set; }
        public string room_area { get; set; }
        public string room_floor { get; set; }
        public Nullable<int> room_computer_num { get; set; }
        public Nullable<int> room_state { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_NightDutyReport> HR_NightDutyReport { get; set; }
    }
}
