//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAN.ZHAN.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HR_Employee()
        {
            this.HR_Attendance = new HashSet<HR_Attendance>();
            this.HR_HomeWork = new HashSet<HR_HomeWork>();
            this.HR_NightDutyReport = new HashSet<HR_NightDutyReport>();
            this.HR_RestReport = new HashSet<HR_RestReport>();
        }
    
        public int e_id { get; set; }
        public string e_loginid { get; set; }
        public string e_pwd { get; set; }
        public string e_mobile { get; set; }
        public string e_email { get; set; }
        public Nullable<int> e_state { get; set; }
        public Nullable<int> e_userType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_Attendance> HR_Attendance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_HomeWork> HR_HomeWork { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_NightDutyReport> HR_NightDutyReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_RestReport> HR_RestReport { get; set; }
    }
}
