//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAN.ZHAN.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_MeettingSetting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HR_MeettingSetting()
        {
            this.HR_Attendance = new HashSet<HR_Attendance>();
        }
    
        public int m_id { get; set; }
        public string m_name { get; set; }
        public Nullable<int> m_isOpen { get; set; }
        public string m_master { get; set; }
        public Nullable<System.DateTime> m_start_time { get; set; }
        public Nullable<int> m_state { get; set; }
        public string m_address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_Attendance> HR_Attendance { get; set; }
    }
}
