//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAN.ZHAN.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_NightDutyReport
    {
        public int ndr_n_id { get; set; }
        public Nullable<int> ndr_e_id { get; set; }
        public Nullable<int> room_no { get; set; }
        public string ndr_class_no { get; set; }
        public Nullable<int> ndr_attend_num { get; set; }
        public string ndr_discipline { get; set; }
        public string ndr_work_details { get; set; }
        public Nullable<int> ndr_play_mobile { get; set; }
        public Nullable<int> ndr_play_game { get; set; }
        public Nullable<int> ndr_sleep { get; set; }
        public string ndr_other_situation { get; set; }
        public Nullable<System.DateTime> ndr_record_time { get; set; }
    
        public virtual HR_ClassRoom HR_ClassRoom { get; set; }
        public virtual HR_Employee HR_Employee { get; set; }
    }
}
