//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAN.ZHAN.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_RestReport
    {
        public int rr_id { get; set; }
        public Nullable<int> rr_e_id { get; set; }
        public Nullable<System.DateTime> rest_starttime { get; set; }
        public Nullable<System.DateTime> rest_endtime { get; set; }
        public Nullable<int> rest_state { get; set; }
    
        public virtual HR_Employee HR_Employee { get; set; }
    }
}
