//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAN.ZHAN.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Resource
    {
        public int res_id { get; set; }
        public Nullable<int> hw_id { get; set; }
        public string res_name { get; set; }
    
        public virtual HR_HomeWork HR_HomeWork { get; set; }
    }
}
