//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAN.ZHAN.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NanZhanDBEntities : DbContext
    {
        public NanZhanDBEntities()
            : base("name=NanZhanDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HR_Attendance> HR_Attendance { get; set; }
        public virtual DbSet<HR_ClassRoom> HR_ClassRoom { get; set; }
        public virtual DbSet<HR_Employee> HR_Employee { get; set; }
        public virtual DbSet<HR_HomeWork> HR_HomeWork { get; set; }
        public virtual DbSet<HR_NightDutyReport> HR_NightDutyReport { get; set; }
        public virtual DbSet<HR_Resource> HR_Resource { get; set; }
        public virtual DbSet<HR_RestReport> HR_RestReport { get; set; }
        public virtual DbSet<HR_MeettingSetting> HR_MeettingSetting { get; set; }
        public virtual DbSet<V_Attendance_Emp_Meetting> V_Attendance_Emp_Meetting { get; set; }
    }
}
