//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAN.ZHAN.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Attendance_Emp_Meetting
    {
        public int a_id { get; set; }
        public Nullable<int> e_id { get; set; }
        public Nullable<int> m_id { get; set; }
        public string e_loginid { get; set; }
        public string e_mobile { get; set; }
        public string e_email { get; set; }
        public string m_name { get; set; }
        public Nullable<System.DateTime> m_start_time { get; set; }
        public string m_address { get; set; }
        public Nullable<int> m_isOpen { get; set; }
        public string m_master { get; set; }
        public Nullable<int> m_state { get; set; }
        public Nullable<System.DateTime> a_time { get; set; }
        public Nullable<int> a_attend { get; set; }
    }
}
